#pragma once
// Auto-generated by the Protocol Modeling tool. Do not edit manually.
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include "MB_DDF/Tools/SelfDescribingLog.h"

namespace ProtocolModel {

struct Fk_to_datalink {
    struct BitGroup1_1 {
        uint16_t ins_mode_set : 3; // 指令控制字1.指令工作模式设置
        uint16_t ins_power_set : 2; // 指令控制字1.指令功率设置
        uint16_t ins_frequency_set : 8; // 指令控制字1.指令频点设置
        uint16_t luanch_signal : 2; // 指令控制字1.弹动信号
        uint16_t reserved2 : 1; // 指令控制字1.备份
    };
    struct BitGroup1_2 {
        uint8_t link_check : 2; // 指令控制字2.通信链路检查指令
        uint8_t frequency_response : 2; // 指令控制字2.上下行频率应答方式
        uint8_t antenna_select : 1; // 指令控制字2.天线选择指示
        uint8_t hopping_gap : 2; // 指令控制字2.跳频间隔
    };
    struct BitGroup2 {
        uint16_t fuze_activation : 1; // 导弹回告信号1.引信开机
        uint16_t compilation_flag : 2; // 导弹回告信号1.条件编译标志
        uint16_t fuze_alarm : 1; // 导弹回告信号1.引信报警
        uint16_t detonate_signal : 1; // 导弹回告信号1.起爆信号
        uint16_t protection_unlock : 1; // 导弹回告信号1.安执解保
        uint16_t engine_ignition : 1; // 导弹回告信号1.发动机点火指令
        uint16_t plug_attached : 1; // 导弹回告信号1.脱落在位信号
        uint16_t navigation_valid : 1; // 导弹回告信号3.导航信息有效
        uint16_t target_valid : 1; // 导弹回告信号3.目标信息有效
        uint16_t target_missile_valid : 1; // 导弹回告信号3.目标和导弹信息可用
        uint16_t allow_detection : 1; // 导弹回告信号3.允许检测令
        uint16_t allow_interception_references : 1; // 导弹回告信号3.允许截获跟踪参考
        uint16_t allow_interception_instruction : 1; // 导弹回告信号3.允许截获跟踪指令
        uint16_t angular_velocity_available : 1; // 导弹回告信号3.视线角速度可用
        uint16_t reserved3 : 1; // 导弹回告信号3.备用
    };
    struct BitGroup3_1 {
        uint16_t target_1_pos_l : 16; // 目标1图像位置低16位
    };
    struct BitGroup3_2 {
        uint8_t target_1_pos_h : 8; // 目标1图像位置高8位
    };
    struct BitGroup3_3 {
        uint16_t target_2_pos_l : 16; // 目标2图像位置低16位
    };
    struct BitGroup3_4 {
        uint8_t target_2_pos_h : 8; // 目标2图像位置高8位
    };
    struct BitGroup3_5 {
        uint16_t target_3_pos_l : 16; // 目标3图像位置低16位
    };
    struct BitGroup3_6 {
        uint8_t target_3_pos_h : 8; // 目标3图像位置高8位
    };
    struct BitGroup3_7 {
        uint16_t target_4_pos_l : 16; // 目标4图像位置低16位
    };
    struct BitGroup3_8 {
        uint8_t target_4_pos_h : 8; // 目标4图像位置高8位
    };
    struct BitGroup3_9 {
        uint16_t target_5_pos_l : 16; // 目标5图像位置低16位
    };
    struct BitGroup3_10 {
        uint8_t target_5_pos_h : 8; // 目标5图像位置高8位
    };
    struct BitGroup3_11 {
        uint16_t target_6_pos_l : 16; // 目标6图像位置低16位
    };
    struct BitGroup3_12 {
        uint8_t target_6_pos_h : 8; // 目标6图像位置高8位
    };
    uint8_t domain_id; // 域ID
    uint8_t message_id; // 消息ID
    uint16_t reserved1; // 备份
    uint16_t serial; // 流水号
    uint8_t work_mode_set; // 工作模式设置
    BitGroup1_1 bitGroup1_1;
    BitGroup1_2 bitGroup1_2;
    uint8_t missile_number; // 导弹号
    double missile_pos_north; // 导弹相对弹动点北向位置
    double missile_pos_up; // 导弹相对弹动点天向位置
    double missile_pos_east; // 导弹相对弹动点东向位置
    BitGroup2 bitGroup2;
    uint8_t number_number; // 目标数量和当前目标号
    BitGroup3_1 bitGroup3_1;
    BitGroup3_2 bitGroup3_2;
    BitGroup3_3 bitGroup3_3;
    BitGroup3_4 bitGroup3_4;
    BitGroup3_5 bitGroup3_5;
    BitGroup3_6 bitGroup3_6;
    BitGroup3_7 bitGroup3_7;
    BitGroup3_8 bitGroup3_8;
    BitGroup3_9 bitGroup3_9;
    BitGroup3_10 bitGroup3_10;
    BitGroup3_11 bitGroup3_11;
    BitGroup3_12 bitGroup3_12;
    double image_roll; // 图像滚转角度
    uint32_t reserved4; // 备份
    uint8_t reserved6; // 备份
    uint8_t binding_instruction; // 装订指令号
    uint8_t binding_missile; // 装订导弹号
    uint8_t binding_target; // 装订目标号
    uint32_t reserved5; // 备份
    uint8_t reserved7; // 备份
    uint8_t check1; // 校验1
    uint8_t tail1; // 帧尾1
    uint8_t tail2; // 帧尾2

    // Initialize fields with default values.
    Fk_to_datalink() {
        domain_id = 195;
        message_id = 4;
        reserved1 = 0;
        serial = 0;
        work_mode_set = 90;
        bitGroup1_1.ins_mode_set = 2;
        bitGroup1_1.ins_power_set = 0;
        bitGroup1_1.ins_frequency_set = 1;
        bitGroup1_1.luanch_signal = 0;
        bitGroup1_1.reserved2 = 0;
        bitGroup1_2.link_check = 0;
        bitGroup1_2.frequency_response = 1;
        bitGroup1_2.antenna_select = 0;
        bitGroup1_2.hopping_gap = 1;
        missile_number = 1;
        missile_pos_north = 0;
        missile_pos_up = 0;
        missile_pos_east = 0;
        bitGroup2.fuze_activation = 0;
        bitGroup2.compilation_flag = 0;
        bitGroup2.fuze_alarm = 0;
        bitGroup2.detonate_signal = 0;
        bitGroup2.protection_unlock = 0;
        bitGroup2.engine_ignition = 0;
        bitGroup2.plug_attached = 0;
        bitGroup2.navigation_valid = 0;
        bitGroup2.target_valid = 0;
        bitGroup2.target_missile_valid = 0;
        bitGroup2.allow_detection = 0;
        bitGroup2.allow_interception_references = 0;
        bitGroup2.allow_interception_instruction = 0;
        bitGroup2.angular_velocity_available = 0;
        bitGroup2.reserved3 = 0;
        number_number = 0;
        bitGroup3_1.target_1_pos_l = 0;
        bitGroup3_2.target_1_pos_h = 0;
        bitGroup3_3.target_2_pos_l = 0;
        bitGroup3_4.target_2_pos_h = 0;
        bitGroup3_5.target_3_pos_l = 0;
        bitGroup3_6.target_3_pos_h = 0;
        bitGroup3_7.target_4_pos_l = 0;
        bitGroup3_8.target_4_pos_h = 0;
        bitGroup3_9.target_5_pos_l = 0;
        bitGroup3_10.target_5_pos_h = 0;
        bitGroup3_11.target_6_pos_l = 0;
        bitGroup3_12.target_6_pos_h = 0;
        image_roll = 0;
        reserved4 = 0;
        reserved6 = 0;
        binding_instruction = 1;
        binding_missile = 1;
        binding_target = 1;
        reserved5 = 0;
        reserved6 = 0;
        reserved7 = 0;
        check1 = 0;
        tail1 = 85;
        tail2 = 85;
    }
};

class Fk_to_datalinkProtocol {
public:
    constexpr static size_t FRAME_SIZE = 60;

    // Return byte offset of a member within the frame struct.
    template<typename T, typename Member>
    constexpr static uint32_t offset_of_member(Member T::*member_ptr) {
        return static_cast<uint32_t>(
            reinterpret_cast<uintptr_t>(
                &(static_cast<T*>(nullptr)->*member_ptr)
            )
        );
    }

    // Write 16-bit unsigned integer in little-endian.
    static inline void writeLe16(char* dst, uint16_t value) {
        dst[0] = static_cast<char>(value & 0xFF);
        dst[1] = static_cast<char>((value >> 8) & 0xFF);
    }

    // Write 32-bit unsigned integer in little-endian.
    static inline void writeLe32(char* dst, uint32_t value) {
        dst[0] = static_cast<char>(value & 0xFF);
        dst[1] = static_cast<char>((value >> 8) & 0xFF);
        dst[2] = static_cast<char>((value >> 16) & 0xFF);
        dst[3] = static_cast<char>((value >> 24) & 0xFF);
    }

    // Read 16-bit unsigned integer in little-endian.
    static inline uint16_t readLe16(const char* src) {
        return static_cast<uint8_t>(src[0]) | (static_cast<uint8_t>(src[1]) << 8);
    }

    // Read 32-bit unsigned integer in little-endian.
    static inline uint32_t readLe32(const char* src) {
        return static_cast<uint8_t>(src[0]) | (static_cast<uint8_t>(src[1]) << 8)
            | (static_cast<uint8_t>(src[2]) << 16) | (static_cast<uint8_t>(src[3]) << 24);
    }

    // Encode unsigned value with LSB scaling.
    static inline uint32_t encodeUnsigned(double actual, double lsb) {
        return static_cast<uint32_t>(actual / lsb);
    }

    // Encode signed value with LSB scaling.
    static inline int32_t encodeSigned(double actual, double lsb) {
        return static_cast<int32_t>(actual / lsb);
    }

    // Decode unsigned value with LSB scaling.
    static inline double decodeUnsigned(uint32_t encoded, double lsb) {
        return static_cast<double>(encoded) * lsb;
    }

    // Decode signed value with LSB scaling.
    static inline double decodeSigned(int32_t encoded, double lsb) {
        return static_cast<double>(encoded) * lsb;
    }

    // Pack valid fields into a byte buffer.
    static std::array<char, FRAME_SIZE> packFrame(const Fk_to_datalink& frame) {
        std::array<char, FRAME_SIZE> buffer{};
        buffer[0] = static_cast<char>(frame.domain_id);
        buffer[1] = static_cast<char>(frame.message_id);
        writeLe16(buffer.data() + 2, static_cast<uint16_t>(frame.reserved1));
        writeLe16(buffer.data() + 4, static_cast<uint16_t>(frame.serial));
        buffer[6] = static_cast<char>(frame.work_mode_set);
        uint16_t bitGroup1_1Value = 0;
        bitGroup1_1Value |= (static_cast<uint16_t>(frame.bitGroup1_1.ins_mode_set) & ((1u << 3) - 1u)) << 0;
        bitGroup1_1Value |= (static_cast<uint16_t>(frame.bitGroup1_1.ins_power_set) & ((1u << 2) - 1u)) << 3;
        bitGroup1_1Value |= (static_cast<uint16_t>(frame.bitGroup1_1.ins_frequency_set) & ((1u << 8) - 1u)) << 5;
        bitGroup1_1Value |= (static_cast<uint16_t>(frame.bitGroup1_1.luanch_signal) & ((1u << 2) - 1u)) << 13;
        bitGroup1_1Value |= (static_cast<uint16_t>(frame.bitGroup1_1.reserved2) & ((1u << 1) - 1u)) << 15;
        writeLe16(buffer.data() + 7, bitGroup1_1Value);
        uint8_t bitGroup1_2Value = 0;
        bitGroup1_2Value |= (static_cast<uint8_t>(frame.bitGroup1_2.link_check) & ((1u << 2) - 1u)) << 0;
        bitGroup1_2Value |= (static_cast<uint8_t>(frame.bitGroup1_2.frequency_response) & ((1u << 2) - 1u)) << 2;
        bitGroup1_2Value |= (static_cast<uint8_t>(frame.bitGroup1_2.antenna_select) & ((1u << 1) - 1u)) << 4;
        bitGroup1_2Value |= (static_cast<uint8_t>(frame.bitGroup1_2.hopping_gap) & ((1u << 2) - 1u)) << 5;
        buffer[9] = static_cast<char>(bitGroup1_2Value);
        buffer[10] = static_cast<char>(frame.missile_number);
        writeLe16(buffer.data() + 11, static_cast<uint16_t>(encodeSigned(frame.missile_pos_north, 0.25)));
        writeLe16(buffer.data() + 13, static_cast<uint16_t>(encodeSigned(frame.missile_pos_up, 0.25)));
        writeLe16(buffer.data() + 15, static_cast<uint16_t>(encodeSigned(frame.missile_pos_east, 0.25)));
        uint16_t bitGroup2Value = 0;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.fuze_activation) & ((1u << 1) - 1u)) << 0;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.compilation_flag) & ((1u << 2) - 1u)) << 1;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.fuze_alarm) & ((1u << 1) - 1u)) << 3;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.detonate_signal) & ((1u << 1) - 1u)) << 4;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.protection_unlock) & ((1u << 1) - 1u)) << 5;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.engine_ignition) & ((1u << 1) - 1u)) << 6;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.plug_attached) & ((1u << 1) - 1u)) << 7;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.navigation_valid) & ((1u << 1) - 1u)) << 8;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.target_valid) & ((1u << 1) - 1u)) << 9;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.target_missile_valid) & ((1u << 1) - 1u)) << 10;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.allow_detection) & ((1u << 1) - 1u)) << 11;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.allow_interception_references) & ((1u << 1) - 1u)) << 12;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.allow_interception_instruction) & ((1u << 1) - 1u)) << 13;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.angular_velocity_available) & ((1u << 1) - 1u)) << 14;
        bitGroup2Value |= (static_cast<uint16_t>(frame.bitGroup2.reserved3) & ((1u << 1) - 1u)) << 15;
        writeLe16(buffer.data() + 17, bitGroup2Value);
        buffer[19] = static_cast<char>(frame.number_number);
        uint16_t bitGroup3_1Value = 0;
        bitGroup3_1Value |= (static_cast<uint16_t>(frame.bitGroup3_1.target_1_pos_l) & ((1u << 16) - 1u)) << 0;
        writeLe16(buffer.data() + 20, bitGroup3_1Value);
        uint8_t bitGroup3_2Value = 0;
        bitGroup3_2Value |= (static_cast<uint8_t>(frame.bitGroup3_2.target_1_pos_h) & ((1u << 8) - 1u)) << 0;
        buffer[22] = static_cast<char>(bitGroup3_2Value);
        uint16_t bitGroup3_3Value = 0;
        bitGroup3_3Value |= (static_cast<uint16_t>(frame.bitGroup3_3.target_2_pos_l) & ((1u << 16) - 1u)) << 0;
        writeLe16(buffer.data() + 23, bitGroup3_3Value);
        uint8_t bitGroup3_4Value = 0;
        bitGroup3_4Value |= (static_cast<uint8_t>(frame.bitGroup3_4.target_2_pos_h) & ((1u << 8) - 1u)) << 0;
        buffer[25] = static_cast<char>(bitGroup3_4Value);
        uint16_t bitGroup3_5Value = 0;
        bitGroup3_5Value |= (static_cast<uint16_t>(frame.bitGroup3_5.target_3_pos_l) & ((1u << 16) - 1u)) << 0;
        writeLe16(buffer.data() + 26, bitGroup3_5Value);
        uint8_t bitGroup3_6Value = 0;
        bitGroup3_6Value |= (static_cast<uint8_t>(frame.bitGroup3_6.target_3_pos_h) & ((1u << 8) - 1u)) << 0;
        buffer[28] = static_cast<char>(bitGroup3_6Value);
        uint16_t bitGroup3_7Value = 0;
        bitGroup3_7Value |= (static_cast<uint16_t>(frame.bitGroup3_7.target_4_pos_l) & ((1u << 16) - 1u)) << 0;
        writeLe16(buffer.data() + 29, bitGroup3_7Value);
        uint8_t bitGroup3_8Value = 0;
        bitGroup3_8Value |= (static_cast<uint8_t>(frame.bitGroup3_8.target_4_pos_h) & ((1u << 8) - 1u)) << 0;
        buffer[31] = static_cast<char>(bitGroup3_8Value);
        uint16_t bitGroup3_9Value = 0;
        bitGroup3_9Value |= (static_cast<uint16_t>(frame.bitGroup3_9.target_5_pos_l) & ((1u << 16) - 1u)) << 0;
        writeLe16(buffer.data() + 32, bitGroup3_9Value);
        uint8_t bitGroup3_10Value = 0;
        bitGroup3_10Value |= (static_cast<uint8_t>(frame.bitGroup3_10.target_5_pos_h) & ((1u << 8) - 1u)) << 0;
        buffer[34] = static_cast<char>(bitGroup3_10Value);
        uint16_t bitGroup3_11Value = 0;
        bitGroup3_11Value |= (static_cast<uint16_t>(frame.bitGroup3_11.target_6_pos_l) & ((1u << 16) - 1u)) << 0;
        writeLe16(buffer.data() + 35, bitGroup3_11Value);
        uint8_t bitGroup3_12Value = 0;
        bitGroup3_12Value |= (static_cast<uint8_t>(frame.bitGroup3_12.target_6_pos_h) & ((1u << 8) - 1u)) << 0;
        buffer[37] = static_cast<char>(bitGroup3_12Value);
        writeLe16(buffer.data() + 38, static_cast<uint16_t>(encodeSigned(frame.image_roll, 0.006)));
        writeLe32(buffer.data() + 40, static_cast<uint32_t>(frame.reserved4));
        buffer[44] = static_cast<char>(frame.reserved6);
        buffer[45] = static_cast<char>(frame.binding_instruction);
        buffer[46] = static_cast<char>(frame.binding_missile);
        buffer[47] = static_cast<char>(frame.binding_target);
        writeLe32(buffer.data() + 48, static_cast<uint32_t>(frame.reserved5));
        writeLe32(buffer.data() + 52, static_cast<uint32_t>(frame.reserved6));
        buffer[56] = static_cast<char>(frame.reserved7);
        buffer[57] = static_cast<char>(frame.check1);
        buffer[58] = static_cast<char>(frame.tail1);
        buffer[59] = static_cast<char>(frame.tail2);
        return buffer;
    }

    // Unpack valid fields from a byte buffer.
    static bool unpackFrame(const char* rawData, size_t dataSize, Fk_to_datalink& frame) {
        if ((!rawData) || (dataSize < FRAME_SIZE)) {
            return false;
        }
        frame.domain_id = static_cast<uint8_t>(rawData[0]);
        frame.message_id = static_cast<uint8_t>(rawData[1]);
        frame.reserved1 = readLe16(rawData + 2);
        frame.serial = readLe16(rawData + 4);
        frame.work_mode_set = static_cast<uint8_t>(rawData[6]);
        uint16_t bitGroup1_1Value = readLe16(rawData + 7);
        frame.bitGroup1_1.ins_mode_set = (bitGroup1_1Value >> 0) & ((1u << 3) - 1u);
        frame.bitGroup1_1.ins_power_set = (bitGroup1_1Value >> 3) & ((1u << 2) - 1u);
        frame.bitGroup1_1.ins_frequency_set = (bitGroup1_1Value >> 5) & ((1u << 8) - 1u);
        frame.bitGroup1_1.luanch_signal = (bitGroup1_1Value >> 13) & ((1u << 2) - 1u);
        frame.bitGroup1_1.reserved2 = (bitGroup1_1Value >> 15) & ((1u << 1) - 1u);
        uint8_t bitGroup1_2Value = static_cast<uint8_t>(rawData[9]);
        frame.bitGroup1_2.link_check = (bitGroup1_2Value >> 0) & ((1u << 2) - 1u);
        frame.bitGroup1_2.frequency_response = (bitGroup1_2Value >> 2) & ((1u << 2) - 1u);
        frame.bitGroup1_2.antenna_select = (bitGroup1_2Value >> 4) & ((1u << 1) - 1u);
        frame.bitGroup1_2.hopping_gap = (bitGroup1_2Value >> 5) & ((1u << 2) - 1u);
        frame.missile_number = static_cast<uint8_t>(rawData[10]);
        frame.missile_pos_north = decodeSigned(static_cast<int16_t>(readLe16(rawData + 11)), 0.25);
        frame.missile_pos_up = decodeSigned(static_cast<int16_t>(readLe16(rawData + 13)), 0.25);
        frame.missile_pos_east = decodeSigned(static_cast<int16_t>(readLe16(rawData + 15)), 0.25);
        uint16_t bitGroup2Value = readLe16(rawData + 17);
        frame.bitGroup2.fuze_activation = (bitGroup2Value >> 0) & ((1u << 1) - 1u);
        frame.bitGroup2.compilation_flag = (bitGroup2Value >> 1) & ((1u << 2) - 1u);
        frame.bitGroup2.fuze_alarm = (bitGroup2Value >> 3) & ((1u << 1) - 1u);
        frame.bitGroup2.detonate_signal = (bitGroup2Value >> 4) & ((1u << 1) - 1u);
        frame.bitGroup2.protection_unlock = (bitGroup2Value >> 5) & ((1u << 1) - 1u);
        frame.bitGroup2.engine_ignition = (bitGroup2Value >> 6) & ((1u << 1) - 1u);
        frame.bitGroup2.plug_attached = (bitGroup2Value >> 7) & ((1u << 1) - 1u);
        frame.bitGroup2.navigation_valid = (bitGroup2Value >> 8) & ((1u << 1) - 1u);
        frame.bitGroup2.target_valid = (bitGroup2Value >> 9) & ((1u << 1) - 1u);
        frame.bitGroup2.target_missile_valid = (bitGroup2Value >> 10) & ((1u << 1) - 1u);
        frame.bitGroup2.allow_detection = (bitGroup2Value >> 11) & ((1u << 1) - 1u);
        frame.bitGroup2.allow_interception_references = (bitGroup2Value >> 12) & ((1u << 1) - 1u);
        frame.bitGroup2.allow_interception_instruction = (bitGroup2Value >> 13) & ((1u << 1) - 1u);
        frame.bitGroup2.angular_velocity_available = (bitGroup2Value >> 14) & ((1u << 1) - 1u);
        frame.bitGroup2.reserved3 = (bitGroup2Value >> 15) & ((1u << 1) - 1u);
        frame.number_number = static_cast<uint8_t>(rawData[19]);
        uint16_t bitGroup3_1Value = readLe16(rawData + 20);
        frame.bitGroup3_1.target_1_pos_l = (bitGroup3_1Value >> 0) & ((1u << 16) - 1u);
        uint8_t bitGroup3_2Value = static_cast<uint8_t>(rawData[22]);
        frame.bitGroup3_2.target_1_pos_h = (bitGroup3_2Value >> 0) & ((1u << 8) - 1u);
        uint16_t bitGroup3_3Value = readLe16(rawData + 23);
        frame.bitGroup3_3.target_2_pos_l = (bitGroup3_3Value >> 0) & ((1u << 16) - 1u);
        uint8_t bitGroup3_4Value = static_cast<uint8_t>(rawData[25]);
        frame.bitGroup3_4.target_2_pos_h = (bitGroup3_4Value >> 0) & ((1u << 8) - 1u);
        uint16_t bitGroup3_5Value = readLe16(rawData + 26);
        frame.bitGroup3_5.target_3_pos_l = (bitGroup3_5Value >> 0) & ((1u << 16) - 1u);
        uint8_t bitGroup3_6Value = static_cast<uint8_t>(rawData[28]);
        frame.bitGroup3_6.target_3_pos_h = (bitGroup3_6Value >> 0) & ((1u << 8) - 1u);
        uint16_t bitGroup3_7Value = readLe16(rawData + 29);
        frame.bitGroup3_7.target_4_pos_l = (bitGroup3_7Value >> 0) & ((1u << 16) - 1u);
        uint8_t bitGroup3_8Value = static_cast<uint8_t>(rawData[31]);
        frame.bitGroup3_8.target_4_pos_h = (bitGroup3_8Value >> 0) & ((1u << 8) - 1u);
        uint16_t bitGroup3_9Value = readLe16(rawData + 32);
        frame.bitGroup3_9.target_5_pos_l = (bitGroup3_9Value >> 0) & ((1u << 16) - 1u);
        uint8_t bitGroup3_10Value = static_cast<uint8_t>(rawData[34]);
        frame.bitGroup3_10.target_5_pos_h = (bitGroup3_10Value >> 0) & ((1u << 8) - 1u);
        uint16_t bitGroup3_11Value = readLe16(rawData + 35);
        frame.bitGroup3_11.target_6_pos_l = (bitGroup3_11Value >> 0) & ((1u << 16) - 1u);
        uint8_t bitGroup3_12Value = static_cast<uint8_t>(rawData[37]);
        frame.bitGroup3_12.target_6_pos_h = (bitGroup3_12Value >> 0) & ((1u << 8) - 1u);
        frame.image_roll = decodeSigned(static_cast<int16_t>(readLe16(rawData + 38)), 0.006);
        frame.reserved4 = readLe32(rawData + 40);
        frame.reserved6 = static_cast<uint8_t>(rawData[44]);
        frame.binding_instruction = static_cast<uint8_t>(rawData[45]);
        frame.binding_missile = static_cast<uint8_t>(rawData[46]);
        frame.binding_target = static_cast<uint8_t>(rawData[47]);
        frame.reserved5 = readLe32(rawData + 48);
        frame.reserved6 = readLe32(rawData + 52);
        frame.reserved7 = static_cast<uint8_t>(rawData[56]);
        frame.check1 = static_cast<uint8_t>(rawData[57]);
        frame.tail1 = static_cast<uint8_t>(rawData[58]);
        frame.tail2 = static_cast<uint8_t>(rawData[59]);
        return true;
    }

    // Build schema metadata for valid fields.
    static MB_DDF::Tools::LogSchema buildSchema() {
        MB_DDF::Tools::LogSchema schema;
        using LFT = MB_DDF::Tools::LogFieldType;
        const uint32_t bitGroup1_1_offset = offset_of_member(&Fk_to_datalink::bitGroup1_1);
        const uint32_t bitGroup1_2_offset = offset_of_member(&Fk_to_datalink::bitGroup1_2);
        const uint32_t bitGroup2_offset = offset_of_member(&Fk_to_datalink::bitGroup2);
        const uint32_t bitGroup3_1_offset = offset_of_member(&Fk_to_datalink::bitGroup3_1);
        const uint32_t bitGroup3_2_offset = offset_of_member(&Fk_to_datalink::bitGroup3_2);
        const uint32_t bitGroup3_3_offset = offset_of_member(&Fk_to_datalink::bitGroup3_3);
        const uint32_t bitGroup3_4_offset = offset_of_member(&Fk_to_datalink::bitGroup3_4);
        const uint32_t bitGroup3_5_offset = offset_of_member(&Fk_to_datalink::bitGroup3_5);
        const uint32_t bitGroup3_6_offset = offset_of_member(&Fk_to_datalink::bitGroup3_6);
        const uint32_t bitGroup3_7_offset = offset_of_member(&Fk_to_datalink::bitGroup3_7);
        const uint32_t bitGroup3_8_offset = offset_of_member(&Fk_to_datalink::bitGroup3_8);
        const uint32_t bitGroup3_9_offset = offset_of_member(&Fk_to_datalink::bitGroup3_9);
        const uint32_t bitGroup3_10_offset = offset_of_member(&Fk_to_datalink::bitGroup3_10);
        const uint32_t bitGroup3_11_offset = offset_of_member(&Fk_to_datalink::bitGroup3_11);
        const uint32_t bitGroup3_12_offset = offset_of_member(&Fk_to_datalink::bitGroup3_12);
        schema.addFieldAt("域ID", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::domain_id));
        schema.addFieldAt("消息ID", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::message_id));
        schema.addFieldAt("备份", LFT::UInt16, 1, offset_of_member(&Fk_to_datalink::reserved1));
        schema.addFieldAt("流水号", LFT::UInt16, 1, offset_of_member(&Fk_to_datalink::serial));
        schema.addFieldAt("工作模式设置", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::work_mode_set));
        schema.addBitFieldAt("指令控制字1.指令工作模式设置", LFT::UInt16, 0, 3, bitGroup1_1_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("指令控制字1.指令功率设置", LFT::UInt16, 3, 2, bitGroup1_1_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("指令控制字1.指令频点设置", LFT::UInt16, 5, 8, bitGroup1_1_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("指令控制字1.弹动信号", LFT::UInt16, 13, 2, bitGroup1_1_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("指令控制字1.备份", LFT::UInt16, 15, 1, bitGroup1_1_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("指令控制字2.通信链路检查指令", LFT::UInt8, 0, 2, bitGroup1_2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("指令控制字2.上下行频率应答方式", LFT::UInt8, 2, 2, bitGroup1_2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("指令控制字2.天线选择指示", LFT::UInt8, 4, 1, bitGroup1_2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("指令控制字2.跳频间隔", LFT::UInt8, 5, 2, bitGroup1_2_offset, 0, LFT::UInt8);
        schema.addFieldAt("导弹号", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::missile_number));
        schema.addFieldAt("导弹相对弹动点北向位置", LFT::Float64, 1, offset_of_member(&Fk_to_datalink::missile_pos_north));
        schema.addFieldAt("导弹相对弹动点天向位置", LFT::Float64, 1, offset_of_member(&Fk_to_datalink::missile_pos_up));
        schema.addFieldAt("导弹相对弹动点东向位置", LFT::Float64, 1, offset_of_member(&Fk_to_datalink::missile_pos_east));
        schema.addBitFieldAt("导弹回告信号1.引信开机", LFT::UInt16, 0, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号1.条件编译标志", LFT::UInt16, 1, 2, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号1.引信报警", LFT::UInt16, 3, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号1.起爆信号", LFT::UInt16, 4, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号1.安执解保", LFT::UInt16, 5, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号1.发动机点火指令", LFT::UInt16, 6, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号1.脱落在位信号", LFT::UInt16, 7, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号3.导航信息有效", LFT::UInt16, 8, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号3.目标信息有效", LFT::UInt16, 9, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号3.目标和导弹信息可用", LFT::UInt16, 10, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号3.允许检测令", LFT::UInt16, 11, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号3.允许截获跟踪参考", LFT::UInt16, 12, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号3.允许截获跟踪指令", LFT::UInt16, 13, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号3.视线角速度可用", LFT::UInt16, 14, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("导弹回告信号3.备用", LFT::UInt16, 15, 1, bitGroup2_offset, 0, LFT::UInt8);
        schema.addFieldAt("目标数量和当前目标号", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::number_number));
        schema.addBitFieldAt("目标1图像位置低16位", LFT::UInt16, 0, 16, bitGroup3_1_offset, 0, LFT::UInt16);
        schema.addBitFieldAt("目标1图像位置高8位", LFT::UInt8, 0, 8, bitGroup3_2_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("目标2图像位置低16位", LFT::UInt16, 0, 16, bitGroup3_3_offset, 0, LFT::UInt16);
        schema.addBitFieldAt("目标2图像位置高8位", LFT::UInt8, 0, 8, bitGroup3_4_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("目标3图像位置低16位", LFT::UInt16, 0, 16, bitGroup3_5_offset, 0, LFT::UInt16);
        schema.addBitFieldAt("目标3图像位置高8位", LFT::UInt8, 0, 8, bitGroup3_6_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("目标4图像位置低16位", LFT::UInt16, 0, 16, bitGroup3_7_offset, 0, LFT::UInt16);
        schema.addBitFieldAt("目标4图像位置高8位", LFT::UInt8, 0, 8, bitGroup3_8_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("目标5图像位置低16位", LFT::UInt16, 0, 16, bitGroup3_9_offset, 0, LFT::UInt16);
        schema.addBitFieldAt("目标5图像位置高8位", LFT::UInt8, 0, 8, bitGroup3_10_offset, 0, LFT::UInt8);
        schema.addBitFieldAt("目标6图像位置低16位", LFT::UInt16, 0, 16, bitGroup3_11_offset, 0, LFT::UInt16);
        schema.addBitFieldAt("目标6图像位置高8位", LFT::UInt8, 0, 8, bitGroup3_12_offset, 0, LFT::UInt8);
        schema.addFieldAt("图像滚转角度", LFT::Float64, 1, offset_of_member(&Fk_to_datalink::image_roll));
        schema.addFieldAt("备份", LFT::UInt32, 1, offset_of_member(&Fk_to_datalink::reserved4));
        schema.addFieldAt("备份", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::reserved6));
        schema.addFieldAt("装订指令号", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::binding_instruction));
        schema.addFieldAt("装订导弹号", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::binding_missile));
        schema.addFieldAt("装订目标号", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::binding_target));
        schema.addFieldAt("备份", LFT::UInt32, 1, offset_of_member(&Fk_to_datalink::reserved5));
        schema.addFieldAt("备份", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::reserved7));
        schema.addFieldAt("校验1", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::check1));
        schema.addFieldAt("帧尾1", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::tail1));
        schema.addFieldAt("帧尾2", LFT::UInt8, 1, offset_of_member(&Fk_to_datalink::tail2));
        return schema;
    }
};

} // namespace ProtocolModel